FROM nginx:latest
#ARG FRONTEND_DIR_PATH
#RUN echo "Dockerfile FRONTEND_DIR_PATH: $FRONTEND_DIR_PATH"
#ADD  $FRONTEND_DIR_PATH/dist/BusinessAssistantBCN-frontend2 "/opt/BusinessAssistantBCN-frontend2/"
ADD ./dist/BusinessAssistantBCN-frontend2 "/opt/BusinessAssistantBCN-frontend2/"
EXPOSE 80