spring:
  application:
    name: businessassistant-login
  jmx:
    enabled: true

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  datasource:
    signUpUrl: /businessassistantbcn/api/v1/login
    secret: SgVkYp3s6v9y$B&E)H+MbQeThWmZq4t7
    headerString: Authorization
    # Mind the trailing white space below!
    tokenPrefix: Bearer 
    # 10 hours, expressed in milliseconds
    expiresIn: 36_000_000
    authoritiesClaim: authorities
    err: Auth Error, Token Unavailable

logging:
  level:
    root: INFO
    "[org.springframework]": ERROR
    "[com.businessassistantbcn]": INFO
  pattern:
  # console: Spring's default
    file: "%date %5level %-40.40logger{39} [%thread] %msg%n"
#  file:
#    name: login.log
